import Navbar from "../../Navbar";

export default function BoxingPage() {
  return (
    <main dir="rtl" className="min-h-screen bg-[#f4f7f7] text-[#17212a]">
      <Navbar />
      <section className="relative overflow-hidden bg-[#0b2234] px-6 py-24 text-white md:py-32">
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(11,34,52,.97),rgba(11,34,52,.72),rgba(11,34,52,.3)),url('https://commons.wikimedia.org/wiki/Special:FilePath/Boxing%20match%20-%20Wikimedia.jpg')] bg-cover bg-center" />
        <div className="relative mx-auto max-w-6xl"><div className="max-w-3xl"><div className="text-sm font-black tracking-[0.22em] text-[#7ee7e5]">BOXING · OLYMPIC SPORT</div><h1 className="mt-6 text-6xl font-black leading-none md:text-8xl">אגרוף</h1><p className="mt-8 text-2xl font-bold leading-relaxed md:text-4xl">כוח. מהירות. דיוק.<br />אופי שנבנה בכל סיבוב.</p><p className="mt-6 text-lg leading-9 text-slate-200">ענף ספורט עתיק שהתפתח מתחרות לחימה מסורתית לאחד מענפי הספורט המודרניים והאולימפיים המזוהים ביותר עם משמעת, טכניקה ונחישות.</p><div className="mt-8 flex flex-wrap gap-3 text-sm font-bold"><span className="rounded-full bg-white/10 px-5 py-3">ענף אולימפי</span><span className="rounded-full bg-white/10 px-5 py-3">ילדים ומבוגרים</span><span className="rounded-full bg-white/10 px-5 py-3">טכניקה וכושר</span></div><a href="/leave-details" className="mt-9 inline-flex rounded-full bg-[#18b6b4] px-8 py-4 font-black text-white">הרשמה לאימון ניסיון חינם</a></div></div>
      </section>
      <section className="px-6 py-20 md:py-24"><div className="mx-auto max-w-6xl"><div className="max-w-3xl"><div className="text-sm font-black text-[#159c9a]">על הענף</div><h2 className="mt-3 text-4xl font-black md:text-5xl">מהו אגרוף?</h2><p className="mt-6 text-lg leading-9 text-slate-600">אגרוף הוא ספורט קרבי תחרותי שבו שני מתאגרפים מתמודדים במסגרת כללים ברורים, כפפות וציוד מגן. הצלחה בו דורשת שילוב של עבודת רגליים, הגנה, תזמון, דיוק, כושר גופני וקבלת החלטות תחת לחץ.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["🥊","טכניקה","עמידה, עבודת רגליים, הגנה ושילובי מכות."],["⚡","מהירות","תגובה, תזמון ויכולת לשנות קצב."],["🫀","כושר","סבולת, כוח, זריזות והתאוששות בין סיבובים."],["🧠","אופי","משמעת, ביטחון עצמי, התמדה וכבוד ליריב."]].map(([icon,title,text])=><div key={title} className="rounded-3xl bg-white p-7 shadow-md"><div className="text-3xl">{icon}</div><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mt-2 leading-7 text-slate-500">{text}</p></div>)}</div><div className="mt-10 flex justify-center"><a href="/boxing/about" className="rounded-full border-2 border-[#18b6b4] bg-white px-8 py-4 text-lg font-black transition hover:bg-[#18b6b4] hover:text-white">🥊 ללמוד את סיפור האגרוף ←</a></div></div></section>
      <section className="bg-[#0b2234] px-6 py-20 text-white md:py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><div className="text-sm font-black tracking-[0.2em] text-[#7ee7e5]">THE COACH</div><h2 className="mt-3 text-4xl font-black">המאמן</h2></div><div className="mx-auto mt-12 max-w-4xl overflow-hidden rounded-[32px] bg-white/5 p-8 md:p-10"><div className="md:flex md:items-center md:gap-10"><div className="flex h-40 w-40 shrink-0 items-center justify-center rounded-3xl bg-[#18b6b4]/15 text-7xl">🥊</div><div className="mt-7 md:mt-0"><h3 className="text-3xl font-black">סרגיי צ'ומצ'נקו</h3><div className="mt-2 font-bold text-[#7ee7e5]">מאמן אגרוף · אלוף ישראל לשעבר</div><p className="mt-5 leading-8 text-slate-300">סרגיי היה אלוף ישראל באגרוף, התחרה ברמות בינלאומיות וכיום מאמן מתאגרפים באשקלון. בין היתר, הוא מאמן כיום את אלופת ישראל.</p><a href="/boxing/sergey" className="mt-6 inline-flex rounded-full bg-[#18b6b4] px-6 py-3 font-black text-white">לפרופיל המאמן ←</a></div></div></div></div></section>
      <section className="px-6 py-20"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-2"><div className="rounded-3xl bg-[#159c9a] p-8 text-white"><div className="text-sm font-black text-teal-100">קבוצות</div><h2 className="mt-3 text-3xl font-black">ילדים ומבוגרים</h2><p className="mt-4 leading-8 text-teal-50">אימונים המותאמים לגיל ולרמה, עם דגש על יסודות, כושר, טכניקה, משמעת והתקדמות אישית.</p></div><div className="rounded-3xl bg-white p-8 shadow-md"><div className="text-sm font-black text-[#159c9a]">פעילות</div><h2 className="mt-3 text-3xl font-black">ימי ושעות אימון</h2><div className="mt-5 space-y-2 leading-8 text-slate-600"><p><strong>ראשון, שני ורביעי</strong></p><p><strong>ילדים:</strong> 18:00–19:00</p><p><strong>מבוגרים:</strong> 19:00–20:30</p></div><div className="mt-5 font-bold">📍 יעקב גרופר 15, אשקלון</div></div></div></section>
      <section className="bg-[#0b2234] px-6 py-20 text-center text-white"><div className="mx-auto max-w-3xl"><div className="text-6xl">🥊</div><h2 className="mt-6 text-4xl font-black">מוכנים להיכנס לזירה?</h2><p className="mt-5 leading-8 text-slate-300">פנו למאמן סרגיי וקבלו פרטים על האימונים והצטרפות.</p><a href="tel:0548033178" className="mt-8 inline-flex rounded-full bg-[#18b6b4] px-8 py-4 font-black text-white">054-8033178 · התקשרו עכשיו</a></div></section>
    </main>
  );
}
