"use client";

import { useState } from "react";
import Navbar from "../../../Navbar";

const pages = [
  { number: 1, era: "המקורות הקדומים", title: "מסורת של אלפי שנים", paragraphs: ["הסייף המודרני נולד מתוך מסורת עתיקה של שימוש בחרב ללחימה, להגנה עצמית ולדו־קרב. כבר בעולם העתיק כלי נשק דמויי חרב שימשו לא רק בשדה הקרב אלא גם באימונים ובמפגנים של מיומנות.", "במצרים העתיקה קיימות עדויות לתחרויות לחימה מאורגנות שבהן נעשה שימוש בכלי נשק מוגנים. אחת העדויות המפורסמות מתוארכת לסביבות 1190 לפנה״ס ומראה כי כבר לפני יותר מ־3,000 שנה התקיימו אירועים שבהם לחימה בחרבות קיבלה אופי תחרותי.", "עם זאת, חשוב להבחין בין אותן תחרויות קדומות לבין הסייף שאנו מכירים כיום: הספורט המודרני התפתח בהדרגה מתוך מסורות לחימה אירופיות, ולא נוצר באירוע אחד."] },
  { number: 2, era: "ימי הביניים והרנסנס", title: "מהחרב בשדה הקרב אל בית הספר לסייף", paragraphs: ["בימי הביניים הייתה החרב כלי לחימה מרכזי באירופה. לוחמים ואנשי צבא נדרשו ללמוד שליטה בחרב, והידע עבר ממורים לתלמידים באמצעות מסורות של אימון ותרגול.", "בתקופת הרנסנס, ובעיקר במאות ה־16 וה־17, התפתחו באירופה בתי ספר מקצועיים לסייף. הסייף הפך למערכת מסודרת של טכניקות, עמדות, צעדים, התקפות והגנות, ולמקצוע שנלמד באופן שיטתי.", "בהדרגה נוצר גם הבסיס התרבותי לסייף תחרותי: במקום להשתמש בחרב כדי לפגוע ביריב באמת, המתאמנים החלו להשתמש בכלי אימון ובציוד מגן ולפתח כללים שמאפשרים לבחון מיומנות, מהירות ודיוק בבטיחות יחסית."] },
  { number: 3, era: "המאה ה־17 עד המאה ה־19", title: "הולדת הסייף כספורט", paragraphs: ["במאות ה־17 וה־18 החל הסייף לקבל את הצורה המוכרת לנו כיום. התפתח הרומח הקל לאימון, הומצאה מסכת הרשת שהגנה על הפנים, ונוצרו כללים ברורים יותר לגבי אזורי המטרה ואופן ניהול הקרב.", "המעבר מכלי נשק צבאיים לכלי ספורט קלים ובטוחים יותר היה צעד מכריע. עם ירידת חשיבות החרב בשדה הקרב בעקבות כלי הנשק המודרניים, הסייף יכול היה להשתחרר בהדרגה מתפקידו הצבאי ולהפוך לענף ספורט בפני עצמו.", "במאה ה־19 התבססו בתי ספר ומועדוני סייף ברחבי אירופה, נערכו תחרויות, נכתבו תקנונים ונוצרו מסגרות שאפשרו לספורטאים ממדינות שונות להתחרות לפי חוקים דומים."] },
  { number: 4, era: "הסייף האולימפי", title: "מאירופה אל הבמה הגדולה בעולם", paragraphs: ["הסייף היה אחד מענפי הספורט שנכללו כבר במשחקים האולימפיים הראשונים של העת החדשה באתונה בשנת 1896, והוא אחד מחמשת הענפים שהופיעו בכל מהדורות המשחקים האולימפיים המודרניים.", "במשחקי פריז 1900 נוספה תחרות הדקר. במהלך המאה ה־20 הורחב הענף בהדרגה גם לנשים ולתחרויות קבוצתיות, ושלושת כלי הסייף – רומח, דקר וחרב – הפכו לחלק קבוע מהמערכת התחרותית הבינלאומית.", "בשנת 1913 הוקמה הפדרציה הבינלאומית לסייף (FIE), שהפכה לגוף המרכזי המנהל את הספורט בעולם ומפתחת את החוקים והמסגרות הבינלאומיות שלו.", "הטכנולוגיה שינתה גם היא את הענף: מערכת הניקוד האלקטרונית אפשרה לזהות פגיעות באופן מדויק יותר והפכה את הקרבות למהירים, מדידים והוגנים יותר."] },
  { number: 5, era: "1942–1965", title: "הסייף מגיע לישראל", paragraphs: ["בישראל החלה התפתחות מאורגנת של הסייף עוד לפני הקמת המדינה, ובשנות ה־50 וה־60 נבנתה תשתית שאפשרה לסייפים ישראלים לצאת לתחרויות בינלאומיות.", "בשנת 1958 יצאה נבחרת של אגודת הספורט האקדמית (ASA) לתחרויות בפולין. לפי איגוד הסייף הישראלי, זו הייתה אחת ההופעות הראשונות של ספורט ישראלי בכלל בזירה האירופית וההופעה הבינלאומית הראשונה של נבחרת סייף ישראלית.", "בשנת 1960 הופיעו סייפים ישראלים לראשונה במשחקים האולימפיים ברומא. מיקי רון ודוד ואן גלדר השתתפו בתחרויות הסייף, ובכך נפתח הפרק האולימפי של הסייף הישראלי.", "בשנות ה־60, לאחר תקופה של פעילות מצומצמת, יזמו סייפי רמת גן מערכת קבועה של תחרויות מקומיות וארציות. בהמשך נפתחו מועדונים נוספים ונבנתה מסגרת ארצית יציבה יותר."] },
  { number: 6, era: "ההתבססות בישראל", title: "מענף קטן לענף תחרותי", paragraphs: ["התרחבות המועדונים והכשרת מאמנים יצרו בישראל בסיס רחב יותר לסייף. במהלך השנים התפתחו מסגרות לילדים, לנוער ולבוגרים, וסייפים ישראלים החלו להופיע באופן קבוע באליפויות אירופה, אליפויות עולם, גביעי עולם ובמשחקים האולימפיים.", "אחד השלבים החשובים היה המעבר מהתמקדות היסטורית ברומח להתפתחות משמעותית גם בדקר ובחרב. כיום שלושת כלי הסייף מתקיימים בישראל במסגרת תחרותית מסודרת.", "איגוד הסייף הישראלי מציין כי בישראל פועלים כיום יותר מ־19 מועדונים, מצפון הארץ ועד באר שבע, וכי המועדונים הישראלים שולחים ספורטאים ושופטים לתחרויות בינלאומיות ולמשחקים האולימפיים."] },
  { number: 7, era: "הישגים ישראליים בולטים", title: "ישראל על מפת הסייף העולמית", achievements: ["אודי כרמי – מקום 4 באליפות העולם ברומח בשנת 1987.", "לידיה חטואל – מקום 7 באליפות העולם ברומח בשנת 1991.", "תומר אור – אלוף עולם לנוער, דורג בין עשרת הסייפים הטובים בעולם וזכה בשלושה גביעי עולם; השתתף באולימפיאדת בייג׳ינג 2008.", "דלילה חטואל – זכתה בגביעי עולם והגיעה למקום 7 באליפויות אירופה ב־2007 וב־2008; השתתפה באולימפיאדת בייג׳ינג 2008.", "מאור חטואל – זכה במקום השני באליפות אירופה לנוער בשנת 2005.", "אורן בסל – זכה במקום השלישי באליפות העולם לנוער בשנת 2006.", "יובל פרייליך – זכה באליפות אירופה בדקר בשנת 2019 והיה לסייף הישראלי הראשון שזכה בתואר אירופי לבוגרים.", "הסייף הישראלי המשיך להופיע במשחקים האולימפיים גם בעידן המודרני; יובל פרייליך ייצג את ישראל בדקר באולימפיאדת פריז 2024."] },
  { number: 8, era: "הסייף כיום", title: "מסורת שממשיכה להתפתח", paragraphs: ["מה שהתחיל כמיומנות לחימה עתיקה הפך במשך מאות שנים לענף ספורט בינלאומי המבוסס על חוקים, בטיחות, טכנולוגיה ותחרות הוגנת. הסייף המודרני משלב מהירות ודיוק עם חשיבה טקטית, שליטה עצמית ויכולת לקבל החלטות בשברי שנייה.", "הדרך שעבר הספורט – מהחרב בשדה הקרב, דרך בתי הספר האירופיים לסייף, ועד לאולימפיאדה ולמועדונים בישראל – היא סיפור של שינוי מתמיד בלי אובדן המסורת.", "גם בישראל הסיפור ממשיך להיכתב: מדור הסייפים הראשון ברומא 1960 ועד להישגים באירופה ובזירה הבינלאומית, הסייף הישראלי ממשיך להתפתח ולהצמיח ספורטאים, מאמנים ומועדונים חדשים.", "וזה בדיוק מה שהופך את הסייף לייחודי: ענף שבו ההיסטוריה נמצאת בכל תנועה – אבל העתיד תמיד נמצא בקרב הבא."] }
];

export default function FencingAboutPage() {
  const [current, setCurrent] = useState(0);
  const page = pages[current];
  const next = () => setCurrent(v => Math.min(v + 1, pages.length - 1));
  const previous = () => setCurrent(v => Math.max(v - 1, 0));
  const split = page.paragraphs ? Math.ceil(page.paragraphs.length / 2) : 0;
  const leftText = page.paragraphs?.slice(0, split) || [];
  const rightText = page.paragraphs?.slice(split) || [];

  return (
    <main dir="rtl" className="min-h-screen overflow-hidden bg-[#050b10] text-[#162b3e]">
      <Navbar />
      <section className="relative min-h-[calc(100vh-80px)] bg-[radial-gradient(circle_at_50%_30%,#26323a_0%,#0c151c_45%,#03070a_100%)] px-3 py-7 md:px-8 md:py-10">
        <div className="pointer-events-none absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_20%_70%,#174b5d_0%,transparent_35%),radial-gradient(circle_at_85%_45%,#704d2d_0%,transparent_28%)]" />
        <div className="relative mx-auto max-w-[1500px]">
          <div className="mb-5 text-center text-white md:mb-7"><div className="text-[10px] font-bold tracking-[0.32em] text-[#1cc3ce] md:text-xs">TEAM ASHKELON • FENCING</div><h1 className="mt-1 text-2xl font-black md:text-4xl">ההיסטוריה של הסייף</h1></div>
          <div className="grid items-start gap-4 lg:grid-cols-[230px_minmax(0,1fr)] xl:gap-6" dir="ltr">
            <aside className="order-2 rounded-2xl border border-white/10 bg-[#07131d]/90 p-3 shadow-2xl backdrop-blur-md lg:order-1" dir="rtl">
              <div className="mb-3 flex items-center justify-between px-2 text-sm font-black text-white"><span>תוכן העניינים</span><span className="text-xl text-[#1cc3ce]">☷</span></div>
              <div className="space-y-0.5">{pages.map((item, index) => <button key={item.number} onClick={() => setCurrent(index)} className={`relative w-full rounded-lg px-3 py-2.5 text-right text-xs font-bold transition ${current === index ? "bg-[#116678] text-white shadow-inner" : "text-white/75 hover:bg-white/10 hover:text-white"}`}>{index + 1}. {item.era}{current === index && <span className="absolute -left-1 top-1/2 -translate-y-1/2 border-y-[8px] border-l-[10px] border-y-transparent border-l-[#1cc3ce]" />}</button>)}</div>
              <a href="/fencing" className="mt-4 flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-4 text-xs font-bold text-white hover:bg-white/10">📖 חזרה לעמוד הסייף</a>
            </aside>
            <div className="order-1 min-w-0 lg:order-2">
              <div className="relative mx-auto max-w-[1120px] rounded-[10px] bg-[#17130f] p-2 shadow-[0_45px_100px_rgba(0,0,0,.75)] md:p-3">
                <div className="relative rounded-[6px] bg-[#cba66e] p-[4px] shadow-[inset_0_0_22px_rgba(0,0,0,.55)]">
                  <div className="absolute -left-2 top-2 bottom-2 w-2 rounded-l-full bg-[#5d452d] shadow-[inset_-2px_0_2px_rgba(255,255,255,.18)] md:-left-3 md:w-3" />
                  <div className="absolute -right-2 top-2 bottom-2 w-2 rounded-r-full bg-[#5d452d] shadow-[inset_2px_0_2px_rgba(255,255,255,.18)] md:-right-3 md:w-3" />
                  <div className="relative grid min-h-[610px] grid-cols-1 overflow-hidden rounded-[3px] bg-[#ead9b9] md:min-h-[650px] md:grid-cols-2" dir="rtl">
                    <article className="relative order-1 border-b border-[#b99e70] p-5 shadow-[inset_10px_0_25px_rgba(75,48,22,.12)] md:order-2 md:border-b-0 md:border-r md:p-9">
                      <div className="pointer-events-none absolute inset-y-0 right-0 w-16 bg-gradient-to-l from-[#76532e]/30 to-transparent" />
                      <div className="relative h-full"><div className="mb-4 flex items-center justify-between text-[10px] font-bold text-[#84653b]"><span>פרק {page.number}</span><span>{page.era}</span></div><h2 className="mb-5 text-2xl font-black leading-tight text-[#102f49] md:text-[2.15rem]">{page.title}</h2><div className="mb-5 h-px bg-[#a98a5d]/50" />{rightText.map((paragraph, i) => <p key={i} className="mb-4 text-[13px] leading-7 text-[#493f32] md:text-sm md:leading-8">{paragraph}</p>)}{page.achievements && <ul className="space-y-2 text-[13px] leading-6 text-[#493f32] md:text-sm">{page.achievements.slice(4).map((item, i) => <li key={i} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#159eaa]" />{item}</li>)}</ul>}<div className="absolute bottom-0 left-1/2 hidden -translate-x-1/2 text-xs text-[#8c7047] md:block">{current * 2 + 2}</div></div>
                    </article>
                    <article className="relative order-2 p-5 shadow-[inset_-10px_0_25px_rgba(75,48,22,.12)] md:order-1 md:p-9">
                      <div className="pointer-events-none absolute inset-y-0 left-0 w-16 bg-gradient-to-r from-[#76532e]/30 to-transparent" />
                      <div className="relative h-full"><div className="mb-4 flex items-center justify-between text-[10px] font-bold text-[#84653b]"><span>{current * 2 + 1}</span><span>ASHKELON FENCING</span></div>{current === 0 && <div className="mb-4 rounded-md border border-[#9d8257]/35 bg-[#d6c09a]/35 p-2 text-center text-4xl">⚔️</div>}<h3 className="mb-5 text-lg font-black text-[#75572f] md:text-xl">{current === 0 ? "שורשים עתיקים של אמנות הלחימה" : current === 4 ? "הדרך של הסייף לישראל" : current === 6 ? "רגעים שעיצבו את הסייף הישראלי" : "פרק בהיסטוריה"}</h3>{leftText.map((paragraph, i) => <p key={i} className="mb-4 text-[13px] leading-7 text-[#493f32] md:text-sm md:leading-8">{paragraph}</p>)}{page.achievements && <ul className="space-y-2 text-[13px] leading-6 text-[#493f32] md:text-sm">{page.achievements.slice(0, 4).map((item, i) => <li key={i} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#159eaa]" />{item}</li>)}</ul>}<div className="absolute bottom-0 left-1/2 hidden -translate-x-1/2 text-xs text-[#8c7047] md:block">{current * 2 + 1}</div></div>
                    </article>
                    <div className="pointer-events-none absolute bottom-0 left-1/2 top-0 hidden w-10 -translate-x-1/2 bg-gradient-to-r from-transparent via-[#694a2b]/25 to-transparent md:block" />
                  </div>
                </div>
                <button onClick={previous} disabled={current === 0} aria-label="העמוד הקודם" className="absolute -left-3 top-1/2 z-10 flex h-12 w-12 -translate-y-1/2 items-center justify-center rounded-full border border-white/20 bg-[#07131d]/95 text-3xl text-white shadow-2xl transition hover:scale-105 disabled:opacity-25 md:-left-6">‹</button>
                <button onClick={next} disabled={current === pages.length - 1} aria-label="העמוד הבא" className="absolute -right-3 top-1/2 z-10 flex h-12 w-12 -translate-y-1/2 items-center justify-center rounded-full border border-white/20 bg-[#07131d]/95 text-3xl text-white shadow-2xl transition hover:scale-105 disabled:opacity-25 md:-right-6">›</button>
              </div>
              <div className="mx-auto mt-4 flex w-fit items-center overflow-hidden rounded-full border border-white/10 bg-[#07131d]/95 text-white shadow-xl" dir="ltr"><button onClick={() => setCurrent(0)} className="px-4 py-2 text-xs opacity-80 hover:opacity-100">☷</button><div className="border-x border-white/10 px-5 py-2 text-sm font-bold">{current * 2 + 1}–{current * 2 + 2} / {pages.length * 2}</div><button onClick={previous} disabled={current === 0} className="px-4 py-2 text-lg disabled:opacity-30">‹</button><button onClick={next} disabled={current === pages.length - 1} className="px-4 py-2 text-lg disabled:opacity-30">›</button></div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
