import Link from "next/link";

const RAW = "https://raw.githubusercontent.com/nikolpatrik/hapoel-ashkelon/main/";
const data: Record<string, {title:string; text:string; image?:string}> = {
  fencing:{title:"Fencing in Ashkelon",text:"A professional fencing club giving young and adult athletes the opportunity to develop, progress and achieve results in Israel and abroad. Fencing combines speed, precision, tactical thinking, concentration, coordination, discipline and perseverance.",image:"fencing-logo.png"},
  boxing:{title:"Boxing in Ashkelon",text:"Boxing develops fitness, discipline, confidence, focus, perseverance and a strong competitive spirit. Training is designed to develop physical ability and personal resilience in a professional sporting environment.",image:"boxing-logo.png"},
  "table-tennis":{title:"Table Tennis in Ashkelon",text:"Table tennis is a competitive and enjoyable sport for different ages. Training develops coordination, concentration, agility, reaction speed and precision.",image:"logo.png"},
  rugby:{title:"Rugby in Ashkelon",text:"Rugby develops fitness, strength, teamwork, perseverance and sporting spirit. Activities include children and youth, adults and tag rugby in schools, with an emphasis on community and teamwork.",image:"logo-rugby.png"},
  about:{title:"About the Association",text:"The Ashkelon Sports Association promotes sports clubs and sporting activity in Ashkelon. Athletes and teams represent the city, and successful athletes can reach Israeli national teams and international competitions."},
  legacy:{title:"Heritage & Memorial",text:"This section presents the heritage and memorial content of the association and the people connected with its sporting history."},
  "join-terms":{title:"Membership Terms",text:"Membership and participation are subject to the association's rules, insurance and medical requirements, photography provisions, judging and transfer procedures, as defined in the membership information."},
  "leave-details":{title:"Join Us",text:"Interested in joining a sports activity or trying a training session? Leave your details or contact Nicole directly on WhatsApp."}
};
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const item=data[slug]??{title:"Ashkelon Sports Association",text:"Welcome to the Ashkelon Sports Association."}; return <main dir="ltr" className="min-h-screen bg-[#f5f7fa] text-[#17263d]"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Link href="/english" className="flex items-center gap-4"><img src={`${RAW}logo.png`} alt="Ashkelon Sports Association" className="h-16 w-auto"/><div><div className="text-xl font-black text-[#102f47]">Ashkelon Sports Association</div><div className="text-xs text-slate-500">Excellence • Community • Sport</div></div></Link><nav className="flex flex-wrap items-center gap-5 font-semibold"><Link href="/english">Home</Link><Link href="/english/about">About</Link><Link href="/english/legacy">Heritage</Link><Link href="/english/join-terms">Membership Terms</Link><a href="/" className="text-[#18b6b4]">עברית</a><a href="/russian" target="_blank" rel="noopener noreferrer" className="text-[#18b6b4]">Русский</a></nav></div></header><section className="bg-gradient-to-br from-[#102f47] via-[#123c59] to-[#18b6b4] px-6 py-20 text-white"><div className="mx-auto max-w-6xl grid items-center gap-10 md:grid-cols-2"><div><div className="text-sm font-bold tracking-[0.2em] text-[#7ee7e5]">ASHKELON SPORTS ASSOCIATION</div><h1 className="mt-4 text-5xl font-black leading-tight">{item.title}</h1><p className="mt-7 text-lg leading-9 text-slate-200">{item.text}</p>{slug.includes("fencing")&&<p className="mt-5 font-bold text-[#7ee7e5]">Professional coaching • Children and adults • Competitions</p>}<a href="https://wa.me/972526781740" target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex rounded-full bg-white px-8 py-4 font-bold text-[#102f47]">Contact Nicole on WhatsApp</a></div>{item.image&&<div className="rounded-[32px] bg-white/10 p-8"><img src={`${RAW}${item.image}`} alt={item.title} className="mx-auto max-h-[360px] w-full object-contain"/></div>}</div></section><section className="px-6 py-20"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black text-[#102f47]">Information</h2><p className="mt-5 max-w-3xl text-lg leading-9 text-slate-600">For current training days, hours, coaches and registration details, please contact the association. Additional verified information will be added as it becomes available.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Rugby","/english/rugby"],["Fencing","/english/fencing"],["Boxing","/english/boxing"],["Table Tennis","/english/table-tennis"]].map(([name,href])=><Link key={href} href={href} className="rounded-2xl bg-white p-5 font-bold shadow hover:shadow-lg">{name} →</Link>)}</div></div></section><footer className="bg-[#0b2234] px-6 py-10 text-center text-white">Ashkelon Sports Association · Excellence • Community • Sport</footer></main>}
