import Navbar from "../../Navbar";

const RAW = "https://raw.githubusercontent.com/nikolpatrik/hapoel-ashkelon/main/";

export default function RugbyPage() {
  return (
    <main dir="rtl" className="min-h-screen bg-[#f5f7fa] text-[#17263d]"><Navbar />
      <section className="bg-gradient-to-br from-[#102f47] via-[#123c59] to-[#18b6b4] px-6 py-24 text-center text-white md:py-32"><div className="mx-auto max-w-5xl"><div className="mb-5 text-sm font-bold tracking-[0.2em] text-[#7ee7e5]">RUGBY • רוגבי 🏉</div><h1 className="text-5xl font-black md:text-7xl">רוגבי באשקלון</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-9 text-slate-200">ספורט קבוצתי המפתח כוח, עבודת צוות, משמעת, ביטחון עצמי, התמדה ויכולת להתמודד עם אתגרים.</p><a href="/leave-details" className="mt-9 inline-flex rounded-full bg-white px-8 py-4 font-bold text-[#102f47]">הרשמה לאימון ניסיון חינם</a></div></section>
      <section className="px-6 py-20 md:py-24"><div className="mx-auto grid max-w-6xl items-center gap-12 md:grid-cols-2"><div><div className="text-sm font-bold text-[#18b6b4]">על הענף</div><h2 className="mt-3 text-4xl font-black text-[#102f47]">מועדון מקצועי ומשפחתי</h2><p className="mt-6 text-lg leading-9 text-slate-600">מועדון רוגבי מקצועי ומשפחתי עם פעילות לילדים, נוער ובוגרים. המסגרת משלבת אימונים מקצועיים, קהילה והנאה מהמשחק.</p><p className="mt-5 text-lg leading-9 text-slate-600">הפעילות כוללת קבוצות ילדים ונוער, קבוצת בוגרים וטאג רוגבי בבתי הספר.</p></div><div className="flex min-h-[360px] items-center justify-center rounded-[32px] bg-white p-8 shadow-xl"><img src={`${RAW}logo-rugby.png`} alt="לוגו רוגבי אשקלון" className="max-h-[360px] w-full object-contain" /></div></div></section>
      <section className="bg-white px-6 py-20"><div className="mx-auto max-w-6xl"><div className="text-center"><div className="text-sm font-bold text-[#18b6b4]">הפעילות שלנו</div><h2 className="mt-3 text-4xl font-black text-[#102f47]">קבוצות ומסגרות</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3">{[["👦","ילדים ונוער","פעילות לילדים ולנוער במסגרת ספורטיבית וקהילתית."],["🏉","בוגרים","קבוצת בוגרים המשלבת אימונים, תחרות ועבודת צוות."],["🏫","טאג רוגבי","פעילות טאג רוגבי בבתי הספר."]].map(([i,t,d])=><div key={t} className="rounded-3xl bg-[#f8fafc] p-8 shadow-sm"><div className="text-4xl">{i}</div><h3 className="mt-5 text-2xl font-black text-[#102f47]">{t}</h3><p className="mt-3 leading-8 text-slate-600">{d}</p></div>)}</div></div></section>
      <section className="px-6 py-20"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-2"><div className="rounded-3xl bg-[#102f47] p-8 text-white"><div className="text-sm font-bold text-[#7ee7e5]">מאמנים</div><h2 className="mt-3 text-3xl font-black">צוות המאמנים</h2><p className="mt-4 leading-8 text-slate-300">שמות המאמנים, התמונות והפרטים המלאים לא נמצאו בחומרים המאומתים הזמינים ולכן לא הוספנו מידע לא מאומת.</p></div><div className="rounded-3xl bg-white p-8 shadow-md"><div className="text-sm font-bold text-[#18b6b4]">מערכת פעילות</div><h2 className="mt-3 text-3xl font-black text-[#102f47]">ימי ושעות פעילות</h2><p className="mt-4 leading-8 text-slate-600">הימים והשעות המדויקים טרם נמצאו בחומרי הפרויקט ולכן יתווספו לאחר אימות.</p></div></div></section>
      <section className="bg-[#102f47] px-6 py-20 text-center text-white"><h2 className="text-4xl font-black">רוצים לנסות?</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-slate-300">הרשמה לאימון ניסיון חינם דרך טופס ההצטרפות.</p><a href="/leave-details" className="mt-8 inline-flex rounded-full bg-[#18b6b4] px-8 py-4 font-bold">השאירו פרטים</a></section>
    </main>
  );
}
